create frontend template
DiamondLightSource/xchemlab pull request #124
Opened 2023-09-27 10:24 UTC by kaimsfd

closes #113

2023-09-27 12:09 UTC, garryod requested changes

2023-09-27 12:09 UTC, garryod commented on .devcontainer/devcontainer.json
> +				"esbenp.prettier-vscode"
Probably still don't want `prettier` in our top level dev container as it's only relevant to the frontend

2023-09-27 12:09 UTC, garryod commented on .github/workflows/backend-code.yml
> -            --deny warnings
Can remove this change as it's not relevant to the PR

2023-09-27 12:09 UTC, garryod commented on .github/workflows/frontend-code.yml
> +#############################
Can get rid of these comments, the yaml itself should be readable to anyone with a basic understanding of actions

2023-09-27 12:09 UTC, garryod commented on .github/workflows/frontend-code.yml
> +    branches: [main]
This should be the same as our other CI

2023-09-27 12:09 UTC, garryod commented on .github/workflows/frontend-code.yml
> +        node-version: [18.x]
We don't need a matrix if just running against one version

2023-09-27 12:09 UTC, garryod commented on .github/workflows/frontend-code.yml
> +      statuses: write
We don't want to give the workflow any permissions which aren't required

2023-09-27 12:09 UTC, garryod commented on .github/workflows/frontend-code.yml
> +          fetch-depth: 0
Do we need all history?

2023-09-27 12:09 UTC, garryod commented on .github/workflows/frontend-code.yml
> +          FILTER_REGEX_EXCLUDE: .*README.md.*
Do we need these? The `GITHUB_TOKEN` should already be passed

2023-09-27 12:09 UTC, garryod commented on .github/workflows/frontend-code.yml
> +        working-directory: frontend/
Would it make sense to use [`Boreles/actions-yarn`](https://github.com/Borales/actions-yarn) here?

2023-09-27 12:09 UTC, garryod commented on frontend/.devcontainer/devcontainer.json
> +    "image": "docker.io/library/node:20.6.0-bookworm",
We probably want to use the `docker-compose` here

2023-09-27 15:38 UTC, garryod requested changes

2023-09-27 15:38 UTC, garryod commented on frontend/package.json
> +      "format": "prettier --jsx-single-quote --print-width 100 --write src/**/*.{ts,tsx,css}"
Would rather we stuck with the defaults, or defined any changes in a `.prettierrc` file if we want to deviate

2023-09-27 15:38 UTC, garryod commented on frontend/tsconfig.json
> +        "allowJs": true,
Would rather deny JS, and only allow TS

2023-09-27 16:03 UTC, gfrn commented on frontend/tsconfig.json
> +        "useUnknownInCatchVariables": false,
Is there any reason to disable typing errors as `unknown` by default?

2023-09-27 16:04 UTC, gfrn commented on frontend/package.json
> +      "@testing-library/user-event": "^13.5.0",
Testing libraries should be `devDependencies`

2023-09-28 10:57 UTC, garryod requested changes

2023-09-28 10:57 UTC, garryod commented on .github/workflows/frontend-code.yml
> +  build:
We should de-duplicate jobs like in our other CI jobs

2023-09-28 10:57 UTC, garryod commented on .github/workflows/frontend-code.yml
> +    name: Lint Code Base
Didn't realise you could name jobs. That's quite nice

2023-09-28 10:57 UTC, garryod commented on .github/workflows/frontend-code.yml
> +        uses: actions/checkout@v4
Can we use fully qualified versions for actions?

2023-09-28 10:57 UTC, garryod commented on .github/workflows/frontend-code.yml
> +    name: Lint Code Base
We don't seem to do any linting in this workflow...

2023-09-28 10:57 UTC, garryod commented on frontend/.gitignore
> +yarn-error.log*
Could we add a comment describing what each section of ignores is for?

2023-09-28 13:35 UTC, garryod commented on .github/workflows/frontend-code.yml
> +  build:
Probably worth the usual comment on this as it's a kinda whacky `if` statement

2023-10-03 15:23 UTC, garryod requested changes
Can we add an `index.ts` file to `src`?

2023-10-03 15:23 UTC, garryod commented on frontend/package.json
> +    "tailwindcss": "^3.0.2"
Remove this

2023-10-03 15:23 UTC, garryod commented on frontend/package.json
> +    "postcss": "^8.4.4",
Remove this

2023-10-03 15:23 UTC, garryod commented on frontend/package.json
> +    "sass-loader": "^12.3.0",
Remove this

2023-10-03 15:23 UTC, garryod commented on frontend/package.json
> +    "jest": "^27.4.3",
Upgrade this to `29.x.x`

2023-10-03 15:23 UTC, garryod commented on frontend/package.json
> +    "jest": "^27.4.3",
`yarn upgrade-interactive`

2023-10-05 07:54 UTC, kaimsfd commented
webpack/babel configs https://gitlab.diamond.ac.uk/lims/pato-frontend

2023-10-06 10:25 UTC, gfrn requested changes

2023-10-06 10:25 UTC, gfrn commented on frontend/config/jest/jest.setup.ts
> +import "@testing-library/jest-dom";
This file is not needed; consider deleting it

2023-10-06 14:19 UTC, garryod requested changes

2023-10-06 14:19 UTC, garryod commented on .github/workflows/eslintrc.yml
> +env:
Do we need an `eslintrc` in workflows? Seems a bit off to me

2023-10-06 14:19 UTC, garryod commented on .github/workflows/frontend-code.yml
> +          dir: "frontend"
Could we move this to a separate `lint` job?

2023-10-06 14:19 UTC, garryod commented on frontend/config/env.js
> +
Doubt prettier is a fan of this... Another CI job?

2023-10-06 14:39 UTC, garryod approved these changes

2023-10-06 14:45 UTC, merged